{
  "hash": "43c4a8b64841080e8dd67a09832517c2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 4\"\ntitle-slide-attributes:\n  data-background-image: images/lake.jpg\n  data-background-size: contain\n  data-background-opacity: \"0.5\"\nsubtitle: \"Math 216: Statistical Thinking\"\nauthor: \"Bastola\"\nformat:\n  revealjs:\n    html-math-method: mathjax\n    mathjax-url: \"https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/MathJax.js\" \n    theme: [default, scss/main.scss]\n    slide-number: true\n    preview-links: auto\n    history: true\n    chalkboard: \n      src: drawings.json\n    transition: slide\n    background-transition: fade    \n    touch: false\n    controls: true\n---\n\n\n\n\n\n## Recap: Student Survey \n\nDataset on 362 responses to a student survey given at one college.\n\n::: font50\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Year      |Gender |Smoke | Height| Weight|  SAT| Pulse|\n|:---------|:------|:-----|------:|------:|----:|-----:|\n|Senior    |M      |No    |     71|    180| 1210|    54|\n|Sophomore |F      |Yes   |     66|    120| 1150|    66|\n|FirstYear |M      |No    |     72|    208| 1110|   130|\n|Junior    |M      |No    |     63|    110| 1120|    78|\n|Sophomore |F      |No    |     65|    150| 1170|    40|\n|Sophomore |F      |No    |     65|    114| 1150|    80|\n|FirstYear |F      |No    |     66|    128| 1320|    94|\n|Sophomore |M      |No    |     74|    235| 1370|    77|\n|Junior    |F      |No    |     61|     NA| 1100|    60|\n|FirstYear |F      |No    |     60|    115| 1370|    94|\n|Sophomore |F      |No    |     65|    140| 1170|    63|\n|FirstYear |M      |No    |     63|    200| 1180|    72|\n|Sophomore |M      |No    |     68|    162| 1150|    54|\n|Junior    |F      |No    |     68|    135| 1300|    66|\n|FirstYear |M      |No    |     68|    193| 1350|    72|\n|FirstYear |F      |No    |     63|    110| 1200|    59|\n|FirstYear |F      |No    |     63|     99| 1200|    88|\n|Sophomore |M      |No    |     72|    165| 1350|    59|\n|Sophomore |F      |No    |     62|    120| 1410|    64|\n|Sophomore |F      |No    |     67|    154| 1000|    72|\n\n\n:::\n:::\n\n\n\n:::\n\n## Histogram\n\n::: font80\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(survey, aes(x = Pulse)) +\n  geom_histogram(binwidth = 5, col = \"gold\", fill = \"maroon\") +\n  labs(\n    title = \"Histogram of pulse rates\",\n    x = \"Pulse\",\n    y = \"Count\"\n  )\n```\n:::\n\n\n\n:::\n:::\n\n## Histogram: Shape\n\n::: bqt\n- **Histogram:** Aggregates values into bins and counts how many cases fall into each bin.\n- Pulse rates are symmetrically distributed around a rate of about 70 beats per minute.\n- **Symmetric distributions** are \"centered\" around a mean and median that are roughly the same in value.\n:::\n\n## Shape and Stats\n\n::: cle6\n- Mean and standard deviation are good summary stats of a symmetric distribution.\n- Similar variation to the left and right of the mean so one measure of SD is fine.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey %>% summarize(mean = mean(Pulse), sd = sd(Pulse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      mean       sd\n1 69.63611 12.10508\n```\n\n\n:::\n:::\n\n\n:::\n\n## Shape: Data Distribution\n\n::: cle7\nIf a distribution of data is **approximately bell-shaped**, about 95% of the data should fall within two standard deviations of the sample mean.\n\n- For a sample: 95% of values between $\\bar{y} - 2s$ and $\\bar{y} + 2s$\n- For a population: 95% of values between $\\mu - 2\\sigma$ and $\\mu + 2\\sigma$\n:::\n\n\n## <i class=\"fa fa-pencil-square-o\" style=\"font-size:48px;color:purple\"> Think-Pair-Share</i> {background=\"#ffdf9e\"}\n\n::: row\n::: left\n![](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExaHM2Z2sxZnN3MDB2ZWd5bWp0czJtMmo0ZTcxbzByMmt3dGNweTFncSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/SOb4AcaDitenU4XKdC/giphy.gif)\n:::\n\n::: right\n\n::: cle14\n::: font80\n  - **Objective:** Understand symmetric distributions through real-world examples.  \n  - **Instructions:** Think of an example, discuss with a partner, and share with the class.  \n\n:::\n:::\n:::\n:::\n\npreservea77202327373402e\n\n\n## Bell-shaped Distribution \n\n::: row\n::: left\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n:::\n\n::: right\n\nThe standard deviation for math SAT scores is closest to\n\n(a) 100  \n(b) 75  \n(c) 200  \n(d) 25\n\n:::\n:::\n\n\n\n\n## Standardizing Data: Z-score\n\n::: cle10\n::: font80\n\nThe z-score of a data value, x, tells us how many standard deviations the value is above or below the mean:\n\n$$ z = \\dfrac{x - \\text{mean}}{\\text{SD}} $$\n\n- E.g., if a value $x$ has $z = -1.5$, then the value $x$ is 1.5 standard deviations below the mean.\n\nIf we standardize all values in a bell-shaped distribution, 95% of all z-scores fall between -2 and 2.\n\n:::\n:::\n\n\n## <i class=\"fa fa-pencil-square-o\" style=\"font-size:48px;color:purple\"> Quiz</i> {background=\"#ffdf9e\"}\n\n::: row\n::: left\n![](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExa2ZkaHo5MG0yMnowaGVuZGIwaWRpNHB2bWtwcXIwYjVsZzFyZDBxeiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8gNQZ9IpkcdiAjfOgN/giphy.gif)\n:::\n\n::: right\n\n::: cle14\n::: font80\n  - **Objective:** Assess understanding of z-scores.  \n  - **Instructions:** Answer the quiz question.  \n\n:::\n:::\n:::\n:::\n\npreservee3465351dd372116\n\n\n\n\n## Shape: Left Skew & Right Skew (Histograms)\n\n::: font50\n::: row\n::: left\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(survey$GPA, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.157942\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(survey$GPA, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.2\n```\n\n\n:::\n:::\n\n\n\n:::\n\n::: right\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(survey$Exercise, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.048747\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(survey$Exercise, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n:::\n\n\n\n:::\n:::\n:::\n\n## Shape: Left Skew & Right Skew (Boxplots)\n\n::: font50\n::: row\n::: left\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(survey$GPA, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.157942\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(survey$GPA, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.2\n```\n\n\n:::\n:::\n\n\n\n:::\n\n::: right\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(survey$Exercise, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.048747\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(survey$Exercise, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n:::\n\n\n\n:::\n:::\n:::\n\n## Shape: Boxplots\n\n::: cle6\n::: font70\n\nA graphical representation of the distribution of a dataset, showing the median, quartiles, and outliers.\n\n- **Box:** Represents the interquartile range (IQR) between the 1st quartile (Q1) and the 3rd quartile (Q3).\n- **Median:** The middle value of the dataset, represented by a line inside the box.\n- **Whiskers:** Extend from the box to the minimum and maximum data points within 1.5 times the IQR.\n- **Outliers:** Data points outside of the whiskers, often represented as individual points.\n\n:::\n:::\n\n## Shape: Boxplots\n\n::: cle12\n::: font70\n[Symmetry:]{.bold-text} If the median is roughly centered within the box, and the whiskers are of similar length, the distribution is likely symmetric.\n\n[Skewness:]{.bold-text}\n\n- **Left-skewed:** The median is closer to the upper quartile (Q3), and the left whisker is longer than the right whisker.\n- **Right-skewed:** The median is closer to the lower quartile (Q1), and the right whisker is longer than the left whisker.\n\n:::\n:::\n\n## Elements of a Box Plot: Inner Fences\n\n::: cle13\n::: font70\n**Lower Inner Fence**: \n$$ \\text{Lower inner fence} = Q_L - 1.5 \\times \\text{IQR} $$\n\n**Upper Inner Fence**:\n$$ \\text{Upper inner fence} = Q_U + 1.5 \\times \\text{IQR} $$\n\nInner fences are critical for identifying what is typically considered potential mild outliers. These are points that are unusual but not extreme. The 1.5 multiplier stretches beyond the box enough to capture data variability while excluding more extreme values.\n:::\n:::\n\n\n\n## Adding a Qualitative Variable: Stats\n\n::: font70\n::: out-t\nUse `group_by()` and `summarise()` to get summary statistics using `dplyr` package to compare distributions across different levels of a qualitative variable.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey %>%\n  group_by(Smoke) %>%\n  summarise(Min = min(Pulse),\n            Q1 = quantile(Pulse, 0.25),\n            Median = median(Pulse),\n            Mean = mean(Pulse),\n            Q3 = quantile(Pulse, 0.75),\n            Max = max(Pulse),\n            SD = sd(Pulse),\n            N = n()) %>% \n  knitr::kable(caption = \"Summary Stats of Smoke Categories\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary Stats of Smoke Categories\n\n|Smoke | Min| Q1| Median|     Mean| Q3| Max|       SD|   N|\n|:-----|---:|--:|------:|--------:|--:|---:|--------:|---:|\n|No    |  35| 61|     69| 69.34069| 77| 130| 12.14980| 317|\n|Yes   |  42| 65|     72| 71.81395| 79|  96| 11.67671|  43|\n\n\n:::\n:::\n\n\n\nSmokers have a slightly higher mean pulse rate than non-smokers (71.8 vs. 69.3).\n\n:::\n\n## Side-by-side Histogram\n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(survey, aes(x = Pulse)) + \n  geom_histogram(binwidth = 4, fill = \"maroon\", col = \"gold\") +\n  facet_wrap(~Smoke)\n```\n:::\n\n\n\n:::\n\n## Side-by-side Boxplot\n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(survey, aes(x = Smoke, y = Pulse)) +\n  geom_boxplot(fill = c(\"maroon\", \"purple\"), col = \"darkgreen\") +\n  labs(x = \"Smoking Status\", y = \"Pulse Rate\")\n```\n:::\n\n\n\n:::\n\n## Stacked Bar Graph \n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(survey, aes(x = Year, fill = Gender)) + \n  geom_bar(position = \"fill\") + \n  scale_fill_manual(values = c(\"maroon\", \"gold\")) +\n  labs(title = \"Proportional Distribution by Year and Gender\", \n       y = \"proportion\", \n       x = \"year\", \n       fill = \"Gender\")\n```\n:::\n\n\n\n:::\n\n## Stacked Bar Graph (Counts)\n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-21-1.png){width=960}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(survey, aes(x = Year, fill = Gender)) + \n  geom_bar(position = \"stack\") + \n  scale_fill_manual(values = c(\"maroon\", \"gold\")) +\n  labs(title = \"Proportional Distribution by Year and Gender\", \n       y = \"proportion\", \n       x = \"year\", \n       fill = \"Gender\")\n```\n:::\n\n\n\n:::\n\n<!--\n\n## <i class=\"fa fa-pencil-square-o\" style=\"font-size:48px;color:purple\"> Interactive Data Exploration</i> {background=\"#ffdf9e\"}\n\n::: row\n::: left\n![](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdDFwMW9zZDYxODJoM3JrODgydHhpMDQxeWlwdWtxamZqNzJnaXhsNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ww9Z3l8wl4szKyRIro/giphy.gif)\n:::\n\n::: right\n\n::: cle14\n::: font80\n  - **Objective:** Explore data distributions interactively.  \n  - **Instructions:** Use the provided tool to adjust variables and observe changes.  \n\n:::\n:::\n:::\n:::\n\npreserve605454d61173e8bb\n\n## <i class=\"fa fa-pencil-square-o\" style=\"font-size:48px;color:purple\"> Group Activities with Real Data</i> {background=\"#ffdf9e\"}\n\n::: row\n::: left\n![](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdWk5OHRjdGpyZnlhcDAzemR1YmxsMmtubmUydnFmYTcyYmU2c2pwMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/54BB7UhX573Qhh8k1l/giphy.gif)\n:::\n\n::: right\n\n::: cle14\n::: font80\n  - **Objective:** Analyze and interpret real-world data.  \n  - **Instructions:** Work in groups to analyze the dataset and present your findings.  \n\n:::\n:::\n:::\n:::\n\npreservefd4b60adfb814136\n\n-->\n\n\n",
    "supporting": [
      "Day4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/countdown/countdown.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/countdown/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {
      "preserve605454d61173e8bb": "<div class=\"countdown\" id=\"timer_3fec8073\" data-update-every=\"1\" tabindex=\"0\" style=\"top:0;right:0;padding:3px 4px;font-size:1em;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">02</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>",
      "preservea77202327373402e": "<div class=\"countdown\" id=\"timer_013b6c0d\" data-update-every=\"1\" tabindex=\"0\" style=\"top:0;right:0;padding:3px 4px;font-size:1em;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">04</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>",
      "preservee3465351dd372116": "<div class=\"countdown\" id=\"timer_105f1a37\" data-update-every=\"1\" tabindex=\"0\" style=\"top:0;right:0;padding:3px 4px;font-size:1em;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">02</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>",
      "preservefd4b60adfb814136": "<div class=\"countdown\" id=\"timer_56782192\" data-update-every=\"1\" tabindex=\"0\" style=\"top:0;right:0;padding:3px 4px;font-size:1em;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">02</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>"
    },
    "postProcess": true
  }
}