---
title: "Activity 9"
subtitle: "MATH 216: Statistical Thinking"
format: html
echo: false
---

```{r setup, include=FALSE}
library(openintro)
library(dplyr)
library(knitr)
library(ggplot2)
```

## Activity 1: Discrete Probability Calculations

**Prompt**: Medical research has shown that a certain type of chemotherapy is successful $70 \%$ of the time when used to treat skin cancer. Suppose five skin cancer patients are treated with this type of chemotherapy, and let $x$ equal the number of successful cures out of the five. The probability distribution for the number of successful cures out of five is given in the following table:

| $x$   | 0     | 1     | 2     | 3     | 4     | 5     |
|-------|-------|-------|-------|-------|-------|-------|
| $p(x)$ | 0.002 | 0.029 | 0.132 | 0.309 | 0.360 | 0.168 |


a. Find $\mu$

\vspace*{1in}


b. Find $\sigma$

\vspace*{1in}


c. Use Chebyshev's rule to approximate the probability that $x$ falls into the interval $\mu \pm 2 \sigma$

\vspace*{1in}

## Activity 2: Calculation of Probability


**Prompt**: Calculate $P(x=2)$ for $X \sim \operatorname{Bin}(5, 0.3)$ using the binomial formula:

  $$
  P(x) = \binom{n}{x} p^x q^{n-x}
  $$

\vspace*{2in}


## Activity 3: Calaulations of Probability

**Prompt**: The Heart Association claims that only 10\% of U.S. adults over 30 years of age meet the minimum requirements established by the President's Council on Fitness, Sports, and Nutrition. Suppose four adults are randomly selected and each is given the fitness test. Let $X$ represent the number of the four adults who pass the fitness test. Is $X$ a binomial random variable? Why? What is the probability of $X=3$ ?

\vspace*{2in}


## Activity 4: Calculations of Probability

**Prompt**: What is the mean, variance, and standard deviation of $\textbf{Bin}[4,0.1]$ , $\textbf{Bin}[40,0.1]$,  and $\textbf{Bin}[400,0.1]$?